name: Recovery Build (Legacy)

on:
  push:
    branches:
      - main  # 実行するブランチを指定

env:
  MANIFEST_URL: 'https://github.com/minimal-manifest-twrp/platform_manifest_twrp_omni'
  MANIFEST_BRANCH: 'twrp-9.0'
  DEVICE_TREE_URL: 'https://github.com/mouseos/android_device_sts-tottori_a05bd'
  DEVICE_TREE_BRANCH: 'main'
  DEVICE_PATH: 'device/sts/a05bd'
  DEVICE_NAME: 'a05bd'
  MAKEFILE_NAME: 'omni_a05bd'
  BUILD_TARGET: 'recovery'
  # COMMON_TREE_URLとCOMMON_PATHを必要に応じて指定してください

jobs:
  build:
    if: github.event.repository.owner.id == github.event.sender.id
    runs-on: ubuntu-20.04
    permissions:
      contents: write
    steps:
    - name: Display Run Parameters
      run: |
        echo "::group::User Environment Variables"
        echo "Manifest URL: $MANIFEST_URL"
        echo "Manifest Branch: $MANIFEST_BRANCH"
        echo "Device Tree URL: $DEVICE_TREE_URL"
        echo "Device Tree Branch: $DEVICE_TREE_BRANCH"
        echo "Device Path: $DEVICE_PATH"
        echo "Device Name: $DEVICE_NAME"
        echo "Makefile Name: $MAKEFILE_NAME"
        echo "Build Target: $BUILD_TARGET.img"
        echo "::endgroup::"
 
    - name: Check Out
      uses: actions/checkout@v3

    - name: Cleanup
      uses: rokibhasansagar/slimhub_actions@main

    - name: Prepare the environment
      run: |
        sudo apt update
        sudo apt -y upgrade
        sudo apt -y install gperf gcc-multilib gcc-10-multilib g++-multilib g++-10-multilib libc6-dev lib32ncurses5-dev x11proto-core-dev libx11-dev tree lib32z-dev libgl1-mesa-dev libxml2-utils xsltproc bc ccache lib32readline-dev lib32z1-dev liblz4-tool libncurses5-dev libsdl1.2-dev libwxgtk3.0-gtk3-dev libxml2 lzop pngcrush schedtool squashfs-tools imagemagick libbz2-dev lzma ncftp qemu-user-static libstdc++-10-dev libncurses5 python3

    - name: Install OpenJDK
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '8'

    - name: Setup SSH Keys
      if: ${{ startsWith(env.MANIFEST_URL, 'git@github.com') }}
      uses: webfactory/ssh-agent@v0.5.4
      with:
          ssh-private-key: |
              ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Install repo
      run: |
        mkdir ~/bin
        curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
        chmod a+x ~/bin/repo
        sudo ln -sf ~/bin/repo /usr/bin/repo
      
    - name: Initialize repo
      run: |
        mkdir workspace
        cd workspace
        echo "workspace-folder=$(pwd)" >> $GITHUB_OUTPUT
        git config --global user.name "azwhikaru"
        git config --global user.email "azwhikaru+37921907@github.com"
        repo init --depth=1 -u $MANIFEST_URL -b $MANIFEST_BRANCH
      id: pwd
          
    - name: Repo Sync
      run: |
        repo sync -j$(nproc --all) --force-sync
      working-directory: workspace
      
    - name: Move repository files
      run: |
        shopt -s extglob
        mv !(device|.github) $DEVICE_PATH/
      working-directory: ${{ steps.pwd.outputs.workspace-folder }}

    - name: Clone common tree
      if: |
        env.COMMON_TREE_URL != null
        && env.COMMON_PATH != null
      run: |
        git clone $COMMON_TREE_URL -b $DEVICE_TREE_BRANCH ./$COMMON_PATH
      working-directory: ${{ steps.pwd.outputs.workspace-folder }}

    - name: Sync Device Dependencies
      run: |
        bash ${GITHUB_WORKSPACE}/scripts/convert.sh $DEVICE_PATH/${{ steps.buildtree.outputs.value }}.dependencies
        repo sync -j$(nproc --all)
      working-directory: ${{ steps.pwd.outputs.workspace-folder }}
      continue-on-error: true

    - name: Set Swap Space
      uses: pierotofy/set-swap-space@master
      with:
        swap-size-gb: 12

    - name: Switch to Python2
      run: |
        sudo apt -y install python
        sudo rm -rf /usr/bin/python
        sudo ln -s /usr/bin/python2 /usr/bin/python
        # sudo ln -s /usr/bin/python3 /usr/bin/python3
      continue-on-error: true

    - name: Building recovery
      run: |
        source build/envsetup.sh
        export ALLOW_MISSING_DEPENDENCIES=true
        lunch $MAKEFILE_NAME-eng && make clean && make $BUILD_TARGETimage -j$(nproc --all)
      working-directory: ${{ steps.pwd.outputs.workspace-folder }}

    - name: Upload to Release
      uses: softprops/action-gh-release@v1
      with:
        files: | 
          workspace/out/target/product/$DEVICE_NAME/$BUILD_TARGET.img
          workspace/out/target/product/$DEVICE_NAME/*.zip
          workspace/out/target/product/$DEVICE_NAME/*vendor*.img
        name: $DEVICE_NAME-${{ github.run_id }}
        tag_name: ${{ github.run_id }}
        body: |
          Manifest: $MANIFEST_BRANCH
          Device: $DEVICE_NAME
          Target: $BUILD_TARGET.img
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
